// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:578022157922:web:2084ad80700d84ff5c2b3b',
    messagingSenderId: '578022157922',
    projectId: 'platia-de9d0',
    authDomain: 'platia-de9d0.firebaseapp.com',
    storageBucket: 'platia-de9d0.firebasestorage.app',
    measurementId: 'G-41ESZ6W1MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:578022157922:android:3dcd8cf023360b3f5c2b3b',
    messagingSenderId: '578022157922',
    projectId: 'platia-de9d0',
    storageBucket: 'platia-de9d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:578022157922:ios:7b2577918343df325c2b3b',
    messagingSenderId: '578022157922',
    projectId: 'platia-de9d0',
    storageBucket: 'platia-de9d0.firebasestorage.app',
    iosBundleId: 'com.example.platia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:578022157922:ios:7b2577918343df325c2b3b',
    messagingSenderId: '578022157922',
    projectId: 'platia-de9d0',
    storageBucket: 'platia-de9d0.firebasestorage.app',
    iosBundleId: 'com.example.platia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:578022157922:web:fd67ca36b055b0775c2b3b',
    messagingSenderId: '578022157922',
    projectId: 'platia-de9d0',
    authDomain: 'platia-de9d0.firebaseapp.com',
    storageBucket: 'platia-de9d0.firebasestorage.app',
    measurementId: 'G-8GRS4KR9C6',
  );
}
